loomnetwork/loomchain

- builtin/plugins/coin/coin.go
- builtin/plugins/karma/karma_test.go
> Investigate KarmaCoin Test

- cmd/loom/dposV3_commands.go
- config/config.go
- e2e/dpos_test.go
Resolve issue #1102 and some fail test on dos_test.go
> set default contractLoader to static and fix dpos_test

- features.go
> Added TGCheckZeroAmount flag

- fnConsensus/reactor.go
> add more logging

- cmd/loom/chainconfig/cmd.go
Changing format style of chain-cfg list-features command from JSON to table.
#1241
> change format style of list-features command

- fnConsensus/reactor.go
> fixing validator set construction

- features.go
> added TGFixERC721Feature flags

- eth/query/block.go
Fix for https://github.com/loomnetwork/loomchain/issues/1263
> Return correct value value for transaction objects

- Makefile
- cmd/loom/gateway/gateway_cmd.go
- cmd/loom/gateway/mapping_cmds.go
A new gateway get-contract-mapping <contract-address> command.
A new gateway list-contract-mappings command.
> Gateway fetch contract mappings

- Jenkinsfile
This oracle is built by another job.
> Don't upload binance_tgoracle to the cloud

- auth/chainconfig_middleware.go
- auth/chainconfig_middleware_test.go
- auth/multi_chain_sigtx_middleware.go
- auth/multi_chain_sigtx_middleware_test.go
- cmd/loom/loom.go
- e2e/eth-1-test.toml
- e2e/eth-2-test.toml
- e2e/eth-7-test.toml
- e2e/eth_test.go
- plugin/vm.go
- rpc/eth/conversion_test.go
- rpc/eth/jsonrpc_conversion.go
- rpc/query_server.go
Implement https://github.com/loomnetwork/loomchain/issues/1268
> eth_getBalance call ethCoin method

- cmd/loom/gateway/gateway_cmd.go
- cmd/loom/gateway/general_cmds.go
> Add ability to update withdrawal fee

- Gopkg.toml
- Makefile
We have already upstreamed the commit we need. The upstream branch and our branch are almost the same, so switching back to the upstream branch.
> Switch back to certusone/yubihsm-go branch

- cmd/loom/chainconfig/cmd.go
- e2e/chainconfig.genesis.json
- e2e/chainconfig.toml
ref:https://github.com/loomnetwork/loomchain/issues/1288
> Show validator names in chain-cfg list-validators output

- e2e/engine/cmd.go
- e2e/node/node.go
> Investigate flaky e2e test

- cmd/loom/dposV3_commands.go
- e2e/dpos-downtime.toml
- e2e/dpos-jail-validator.toml
This PR change dpos3 downtime-record response from JSON to table.
Subtask of  https://github.com/loomnetwork/loomchain/issues/1287
> Change dpos3 downtime record response 

- Makefile
This PR adds `gateway` tags for validator-tools so it can be built with the gateway build variant.
> Validator Tool Gateway Build Variant

- Makefile
- app.go
- builtin/plugins/chainconfig/chainconfig.go
- e2e/loom-4-genesis.json
- e2e/loom-4-test.toml
- plugin/fake_context.go
- plugin/vm.go
Uses New Solution which does not induce redundancy in loomchain.State and ChainConfig Context
> Show features enabled by migration in list features

- throttle/contract_tx_limiter_middleware.go
1)Map Loading Times
2)Contract Tx Middleware Execution Latency
> Add Metrics for Contract Tx Limiter Middleware

- builtin/plugins/chainconfig/chainconfig.go
Sort output of List-features chainconfig go contract
> Sort output of List-features chainconfig go contract

- cmd/loom/dposV3_commands.go
- e2e/dpos-downtime.toml
- e2e/dpos-jail-validator.toml
ref : https://github.com/loomnetwork/loomchain/issues/1355
> Renaming dpos3 downtime-record response column title

- eth/polls/eth_subscribe.go
- eth/polls/polls_test.go
- rpc/query_server.go
Fix for https://github.com/loomnetwork/loomchain/issues/1344
> Fix concurrent map read/write in EthSubscriptions

- e2e/eth-1-test.toml
- rpc/instrumenting.go
- rpc/mock_query_server.go
- rpc/query_server.go
- rpc/query_service.go
implements https://github.com/loomnetwork/loomchain/issues/1347
> Make eth_getTransactionReceipt to return null result when receipt isn't found

- store/multi_writer_app_store_test.go
> Add unit tests for MultiWriterAppStore snapshot with IAVLFlushInterval

- cmd/loom/config.go
- evm/evm.go
- features.go
> upgrade evm

- Makefile
- builtin/plugins/user_deployer_whitelist/user_deployer_whitelist.go
- cmd/loom/userdeployerwhitelist/cmd.go
- e2e/middleware_test.go
- e2e/userdeployerwhitelist.toml
> Allow swapping deployer keys in UserWhitelistContract

- app.go
> Collect latency metrics in Application BeginBlock & EndBlock

- fnConsensus/registry.go
> Add Mutual exclusion to InMemoryFnRegistry GetAll method

- config/config.go
- e2e/node/config.go
> Detailed Genesis Load Error Message

- eth/query/eth.go
- rpc/query_server.go
Issue: https://github.com/loomnetwork/loomchain/issues/1396
> Fix receipt not found error

- eth/subs/reset-hub.go
- eth/subs/ws_subscriber.go
- rpc/client.go
- rpc/json_handler_test.go
- rpc/query_server.go
Fix for https://github.com/loomnetwork/loomchain/issues/1366
> Prevent subscription service closing WebSocket connection

- e2e/node/cluster.go
> Sync binance-gateway owner across nodes

- e2e/tests/receipts/loom.yml
- e2e/tests/truffle/contracts/Migrations.sol
- e2e/tests/truffle/contracts/MyCoin.sol
- e2e/tests/truffle/contracts/MyToken.sol
- e2e/tests/truffle/package.json
- e2e/tests/truffle/truffle-config.js
- e2e/tests/truffle/yarn.lock
- eth/query/block.go
- rpc/query_server.go
Get this running again so we can do better web3 JSON-RPC tests.
> Fix e2e truffle tests

- builtin/plugins/karma/karma_test.go
Karma coin unit test fails sporadically. This PR prints out more info on the contract and request in order to find the root cause.
> Print out more info to investigate "Karma coin test fails sporadically"

- cmd/loom/gateway_reactors.go
- config/config.go
- e2e/node/gateway_config.go
> Timing Issue When Running "loom run" with Gateway Reactors Enabled

- e2e/cmd/new.go
- e2e/coin_test.go
- e2e/common/common.go
- e2e/deploygo_test.go
- e2e/dpos_test.go
- e2e/eth_test.go
- e2e/karma_1_test.go
- e2e/loom_test.go
- e2e/tests/README.md
- e2e/tests/truffle/test/EthFunctions.js
- e2e/throttle_test.go
- jenkins.sh
Addresses https://github.com/loomnetwork/loomchain/issues/1398
https://github.com/loomnetwork/loomchain/pull/1333 caused some issues with the truffle tests that could not be included in https://github.com/loomnetwork/loomchain/pull/1415
Fix truffle tests, mainly setting hex values to the same case.
> Fix truffle tests

- Jenkinsfile
- Jenkinsfile-PR.groovy
> Select specific Node version for build

- Makefile
> Bump up yubihsm-go version

- features.go
a part of loomnetwork/transfer-gateway#72
> add TGGatewayVersion1_1 feature flag

- Makefile
- features.go
- migrations/dposv3_migration.go
- tx_handler/migration_tx_handler.go
- tx_handler/migration_tx_handler_test.go
extract migration tx handler from #1224
go-loom : loomnetwork/go-loom#446
> Add tx handler

- builtin/plugins/karma/karma_test.go
- e2e/eth-1-test.toml
- e2e/eth-6-test.toml
- e2e/tests/truffle/test/NonceHandler.js
Currently, our new truffle test and some of eth e2e tests are still flaky. This PR tries to fix them.
> Fix flaky tests

- cmd/loom/loom.go
ref : https://github.com/loomnetwork/loomchain/issues/1436
> loom reset command now remove evm.db

- features.go
- features/features.go
add feature flag for loomnetwork/transfer-gateway#80 fix
> add feature flag for mismatch chain id

- app.go
- eth/polls/polls_test.go
- eth/query/query_test.go
- plugin/vm_test.go
- receipts.go
- receipts/handler/handler.go
- receipts/handler/handler_test.go
- receipts/leveldb/leveldb.go
- receipts/leveldb/leveldb_test.go
> Remvoe unused state paramter from CommitBlock

- cmd/loom/loom.go
- fnConsensus/fnConsensus_test.go
- fnConsensus/reactor.go
- fnConsensus/store.go
- fnConsensus/types.go
> Fix loadReactorState

- fnConsensus/reactor.go
ref : https://github.com/loomnetwork/loomchain/issues/1457
> Collect metrics for safeSubmitMultiSigned and current nonce in custom reactor

- app.go
- cmd/loom/loom.go
- e2e/tests/receipts/loom.yml
- features/features.go
> Add a feature flag to prevent tx hash mismatch

- builtin/plugins/ethcoin/eth_coin.go
Ref: https://github.com/loomnetwork/loomchain/issues/1421
> Add ability to mint ETH via ETHCoin genesis 

- Jenkinsfile
- Makefile
- cmd/loom/replay/no_overrides.go
- cmd/loom/replay/plasmachain_overrides.go
- jenkins.sh
> plasmachain -> basechain

- Dockerfile
> Update download link in Dockerfile

- cmd/loom/gateway/mapping_cmds.go
- cmd/loom/gateway/root_cmd.go
> Add optional json formatter to list-contract-mappings

- auth/auth.go
- auth/auth_test.go
- cmd/loom/handler_test.go
- cmd/loom/loom.go
Addresses https://github.com/loomnetwork/loomchain/issues/1508
Moves NonceTxHandler to loom.go. Use function rather than package-level variables.
> Refactor NonceHandler to allow multiple instances to co-exist

- Jenkinsfile-PR.groovy
Use webhook so that we don't have to poll for changes.
> Use pull request builder plugin

- Jenkinsfile-PR.groovy
> Explicitly define sha1 when updating commit status

- Jenkinsfile-PR.groovy
> Fix syntax

- rpc/eth/jsonrpc_conversion.go
ref : https://github.com/loomnetwork/loomchain/pull/1523#discussion_r331361161
> Quick fix JsonTxCallObject jsontag

- e2e/tests/truffle/contracts/EventTestContract.sol
- e2e/tests/truffle/migrations/5_event_test_contract.js
- e2e/tests/truffle/test/Event.js
- e2e/tests/truffle/test/helpers.js
- eth/subs/d_reset-hub.go
- eth/subs/reset-hub.go
Ref: https://github.com/loomnetwork/loomchain/issues/600
> Fix missing subscription events

- Jenkinsfile-PR.groovy
> Disable PR builds on OSX

- eth/subs/subs_set.go
- rpc/eth/jsonrpc_conversion.go
Add blocktime to subscription events. Addresses https://github.com/loomnetwork/loomchain/issues/1538 .
> Add Blocktime to subscription Events

- e2e/engine/cmd.go
Jenkins OSX machine seems to be taking a while to start the test
clusters.
> Wait a bit longer between cluster readiness pings

- Gopkg.lock
- Gopkg.toml
> Upgrade to latest revision of our Tendermint fork

- fnConsensus/reactor.go
> FnConsensusReactor.handleMaj23VoteSetChannel shouldn't echo voteset to sender

- cmd/loom/loom.go
- config/config.go
- e2e/tests/truffle/test/EthFunctions.js
- e2e/tests/truffle/test/GoContracts.js
- eth/query/eth.go
- eth/query/noevm.go
- eth/query/query_test.go
- evm/config.go
- rpc/eth/config.go
- rpc/query_server.go
> Limit block range

- abci/backend/tendermint.go
- cmd/loom/loom.go
- config/config.go
Issue: https://github.com/loomnetwork/ops/issues/783
> Add a setting to disable mempool.wal

- features/features.go
> Add feature flag to enable fees for LOOM withdrawals via Binance Gateway

- features/features.go
Add TransferGateway feature flag for remove the `TokenWithdrawer` field.
ref : https://github.com/loomnetwork/transfer-gateway/issues/125
PR : https://github.com/loomnetwork/transfer-gateway/pull/126
> Add TransferGateway feature flag.

- evm/evm.go
Issue: https://github.com/loomnetwork/loomchain/issues/1576
> Disable preimage recording in evm state

- Makefile
- cmd/loom/geth.go
- cmd/loom/loom.go
- config/config.go
This PR adds settings to toggle state keys sorting
> Add settings to toggle state keys sorting

- app.go
- builtin/plugins/dposv3/dpos.go
> Exclude bootstrap nodes' delegations from total stake

- builtin/plugins/dposv3/dpos.go
- builtin/plugins/dposv3/dpos_test.go
- features/features.go
ref : https://github.com/loomnetwork/loomchain/issues/1599
> Fix DPOS to claim rewards from all validators

- features/features.go
> add TGVersion1_6 feature flag

- cmd/loom/gateway/general_cmds.go
> Change default Infura ethereum URI

- abci/backend/tendermint.go
- app.go
- cmd/loom/loom.go
This should fix most cases where https://github.com/loomnetwork/loomchain/issues/1615 occurs in practice.
> Load last block header when app starts up before responding to queries

- builtin/plugins/dposv3/dpos_test.go
> Add more DPOS unit test to prevent invalid behaviour

- Jenkinsfile
> Disable OSX builds

- cmd/loom/chainconfig/cmd.go
The power displayed by this command for each validator is the percentage of the validator's current voting power out of the total combined voting power of all currently active validators (known to Tendermint).
> Update chain-cfg list-validators cmd to show individual validator powers

- builtin/plugins/chainconfig/chainconfig_test.go
> chainconfig_test.go: Grammar

- builtin/plugins/deployer_whitelist/deployer_whitelist_test.go
deployer_whitelist_test.go: Grammar
> deployer_whitelist_test.go: Grammar

- builtin/plugins/coin/coin.go
> coin.go: Grammar

- builtin/plugins/karma/upkeep_test.go
> upkeep_test.go: Grammar

- cmd/loom/dposV3_commands.go
When the --concise flag is specified some of the less useful details are omitted from the output.
> Add --concise flag to dpos3 list-delegations cmd

- Jenkinsfile
- Makefile
Add support for ARM on linux, future prs for ARM on OSX
> Add arm processor support (AARCH64 linux)

- Jenkinsfile
> Fix github status tag

- Jenkinsfile
Jenkins node plugin is having trouble installing on aarch64
> Revert to using system nodejs
