Makefile, builtin/plugins/dposv3/dpos.go, builtin/plugins/dposv3/dpos_test.go, builtin/plugins/dposv3/test_helpers.go, cmd/loom/dposV3_commands.go, e2e/dpos-downtime.toml
Currently, a validator address is required to call `dposv3.DowntimeRecord`. This PR makes the method return all validator downtime records if the validator address is not specified.
=> DowntimeRecord returns all validators downtime records 

config/config.go
This makes it easier to deploy the contract to the production cluster
because validators won't have to muck about with loom.yml.
=> Load the UserDeployerWhitelist contract by default

app.go, cmd/loom/loom.go, event.go, evm/evm.go, middleware.go, rpc/query_server_test.go, store/cachingstore.go, store/evmstore.go, store/iavlstore.go, store/multi_writer_app_store.go, store/pruning_iavlstore.go
Prometheus client just released version 1.0.0 on 15 June 2019 which removed default objectives from default summary. So we are required to set objectives manually or the metrics won't show up.
This PR set default objectives for all metrics that use `SummaryOpts`
Ref: https://github.com/prometheus/client_golang/blob/505041cff1d2b843800a4f384694dcf62fb3e69c/CHANGELOG.md
=> Manually set objectives Prometheus metrics

cmd/loom/config.go, config/config.go, config/gateway_config.go, config/no_gateway_config.go
The config now lives in the same package as the oracle.
=> Remove Binance TG Oracle config

e2e/dpos-jail-validator.toml
Currently, `dpos-jail-validator` test is flaky. I am suspecting that the list-candidates request is sent to the cluster before the block height increases so the cluster returns a snapshot of the previous block. This PR fixes the problem by sending a tx to increase block height before querying the candidate list.
=> Fix flaky jailing validator e2e test

e2e/dpos-jail-validator.toml, e2e/engine/cmd.go
Jailing offline validator e2e test is still flaky. I am suspecting that the offline node has not started and downtime periods are not cleared out before we unjail it. As a result, the node is jailed again immediately after it is unjailed. 
The test depends on `Delay` which is not reliable. This PR implements `wait_node_to_start` command that makes the test wait until the offline node has started and downtime periods have been cleared out before unjailing the offline node.
=> Wait the offline node to start before unjailing it

rpc/eth/jsonrpc_conversion.go
fix for https://github.com/loomnetwork/loomchain/issues/1289
=> eth_getTransactionReceipt logs returning caller rather than contract in address field

e2e/chainconfig-routine.toml, e2e/dpos-jail-validator.toml, e2e/engine/cmd.go
The jailing validator is flaky because, after the node starts, its downtime period will not be cleared out until it catches up the other nodes and starts signing blocks. This PR fixes flaky e2e test by adding two commands `wait_block_height_to_increase` and `wait_node_to_catch_up`. So now we can make sure that the node has started and caught up before we unjail it.
=> Fix flaky e2e tests

Gopkg.lock, Gopkg.toml
This is dependency used by the transfer-gateway package, so it needs to
be in the vendor dir when building with TG support.
=> Add back github.com/btcsuite/btcutil/base58 to Gopkg.lock

cmd/loom/chainconfig/cmd.go
Fix response column name.
Now auto adjust by the longest name length.
=> Auto adjust name column length

builtin/plugins/user_deployer_whitelist/user_deployer_whitelist.go, e2e/userdeployerwhitelist.genesis.json, e2e/userdeployerwhitelist.toml, features.go, throttle/contract_tx_limiter_middleware.go, throttle/contract_tx_limiter_middleware_test.go
The new fields added to support per-contract tx limiter cannot be set until the entire cluster has been upgraded.
Also fix e2e test to detect errors & fix divide by zero in tx limiter. The block range for a tier should be non-zero, but if someone forgets to set it on an existing cluster where a previous version of the user deployer whitelist contract was deployed the node shouldn't panic.
=> Put user deployer whitelist contract changes behind a feature flag

Makefile
OSX Jenkins slaves are a bit slow and need more time to run all the tests.
=> Increase test timeout to 35 minutes

e2e/coin-test-loom.yaml, e2e/coin_test.go
`ReceiptsVersion: 2` is the default now, so the two test runs that explicitly set that config setting do exactly the same thing as the two that don't. The 6 & 8 node test runs do exactly the same thing as the 1, 2, and 4 node runs, they're just wasting time and overloading the Jenkins machines.
=> Remove redundant coin e2e test runs

store/block_store.go
=> Fix BlockStore.GetTxResult to return ResponseDeliverTx.Code 

Makefile, auth/chainconfig_middleware_test.go, auth/eth.go, auth/multi_chain_sigtx_middleware.go, auth/multi_chain_sigtx_middleware_test.go, auth/noeth.go, builtin/plugins/address_mapper/address_mapper.go, builtin/plugins/address_mapper/address_mapper_test.go, builtin/plugins/address_mapper/noevm_address_mapper.go, builtin/plugins/plasma_cash/plasma_cash.go, builtin/plugins/plasma_cash/plasma_cash_test.go, cmd/loom/addressmapper.go, cmd/loom/gateway/gateway_cmd.go, cmd/loom/gateway/mapping_cmds.go, cmd/loom/sendtx.go, e2e/loom-4-genesis.json, e2e/loom-4-loom.yaml, e2e/loom-4-test.toml, e2e/loom_test.go, features.go
This PR adds Binance signer to auth middleware so the client can use send txn using Binance private key (in secp256k1 format) with Bitcoin's style address.
=> Add Binance Singed Tx To Auth Middleware

builtin/plugins/dposv3/dpos.go, builtin/plugins/dposv3/dpos_test.go
Negative value response happens when we did not set `ElectionCycleLength` and the election process never happened.
We should just
- set the remaining time untill election to 0 when `ElectionCycleLength` never set before.
ref : #1363
=> Fix time-until-election command show negative response

builtin/plugins/coin/coin.go, builtin/plugins/coin/coin_test.go, builtin/plugins/ethcoin/eth_coin.go, builtin/plugins/ethcoin/eth_coin_test.go, features.go
Since some method in coin contract did't check the value before trying to unmarshal.
So It is possible to unmarshal `nil` variable.
To prevent this we should validate variable before unmarshal.
In order to do that we need ...
- Check the variable before unmarshal. 
- This change needs to be enabled by feature flag `coin:v1.2`
- Add coin contract unit test for flag `coin:v1.2` is enabled.
ref : #902
=> Coin contract need to validate some field in the request

rpc/eth/http_handler.go, rpc/eth/jsonrpc_types.go, rpc/eth/websockets_handler.go
The JSON-RPC can be a number, string, or could be missing entirely,
instead of attempting to decode it into an integer pass it through as is
in the response/error sent back to the client.
=> Make Web3 JSON-RPC endpoint accept string IDs in requests

Makefile, builtin/plugins/dposv3/dpos.go
This PR makes DPOSv3 contract emit an event when a delegation or whitelist amount is slashed. 
Ref: https://github.com/loomnetwork/loomchain/issues/1406
go-loom: https://github.com/loomnetwork/go-loom/pull/439
=> Emit slash delegation event

e2e/engine/cmd.go, e2e/eth-3-test.toml, e2e/eth-4-test.toml, e2e/eth-6-test.toml
This PR adds `wait_for_block_height_to_reach` command to make eth e2e tests more reliable.
Ref: https://github.com/loomnetwork/loomchain/issues/1424
=> Fix flaky eth e2e tests

e2e/tests/truffle/test/EthFunctions.js, eth/query/block.go
When eth_getBlockNumber is called with "latest" as the block number
parameter then block info returned has the block number set as zero,
it should just return the latest block height.
The /eth endpoint appears to work correctly.
=> Fix /query/eth_getBlockByNumber returning zero block number

Makefile, cmd/loom/gateway/gateway_cmd.go, cmd/loom/gateway/general_cmds.go
This PR adds `update-hot-wallet-address` sub command to `gateway` command, which will allow updating hot wallet address state on Transfer Gateway Contract.
=> Add Update Mainnet Hot Wallet Address Cmd

rpc/query_server.go
issue: https://github.com/loomnetwork/loomchain/issues/1471
=> Fix eth_getBalance returns error when ethcoin is not deployed

builtin/plugins/dposv3/dpos.go, features/features.go
It's pointless to jail the validator that is already jailed.
=> Fix jailing jailed validator

Jenkinsfile, Makefile, jenkins.sh
The git SHAs of the various packages used to build the Oracle binaries
are supposed to be filled in via build flags, the flags weren't set
correctly in the loomchain Makefile so the Oracle binaries were being
built with no versioning info. The Oracle targets in the loomchain
Makefile now delegate the actual build to the transfer-gateway Makefile
so that the versioning info is embedded in the Oracle binaries as
intended.
=> Fix missing version info in TG Oracles

cmd/loom/db/db.go, cmd/loom/db/evm.go
This PR adds a new evm state dump command which directly dump state out of evm.db
```
loom db evm-dump-3 --app-height 20  --storage-trie
```
=> Add a new evm state dump command

cmd/loom/config.go, e2e/tests/receipts/genesis.json, e2e/tests/truffle/package.json, e2e/tests/truffle/test/TxHash.js, e2e/tests/truffle/test/helpers.js, e2e/tests/truffle/yarn.lock, evm/loomevm.go, features/features.go
Previously, TxHash generation does not include `from` to calculate tx hash. This PR fixes the issue by using `from` address for calculating tx hash.
=> Fix tx hash generation algo

eth/query/block.go
Currently, `ResponseDeliverTx` of some blocks is missing from statestore for some reason. We need to make sure that `ResponseDeliverTx` is not nil before dereferencing it or the node will panic.
=> Check ResponseDeliverTx before dereferencing

eth/query/block.go
Previously, `GetBlockByNumber` returns TM tx hash for EVM tx if `full` is `false`. This PR makes it return EVM tx hash for EVM tx.
Ref: https://github.com/loomnetwork/loomchain/issues/1501
=> Fix GetBlockByNumber

eth/query/block.go, eth/query/noevm.go, eth/query/query_test.go, eth/query/tx.go, receipts/common/test_helper.go, rpc/query_server.go, store/evm_aux/store.go, store/evm_aux/store_test.go
Currently, there are some non-unique Tx hashes on test clusters due to new Tx hash generation algorithm. So we should not use EVM Tx hash generated for these Txs. This PR replaces non-unique EVM Tx hash with TM Tx hash before responding to queries.
=> Fix non-unique EVM Tx hash

cmd/loom/config.go, features/features.go
Also generate the default genesis with `receipts:v3` disabled since it has been superseded by `receipts:v3.1`
=> Add some notes about how the receipts feature flags interact

app.go
This will allow us to lookup txs that failed in DeliverTx. Probably less
useful to log the tx hash for failed CheckTx, but might be useful for
cross referencing logs between nodes.
=> Log the Tendermint tx hash when logging tx failure in CheckTx/DeliverTx

eth/query/eth.go, receipts/handler/handler.go, rpc/eth/jsonrpc_conversion.go, rpc/query_server.go
Since we introduce child-tx-ref to map TM tx hash with EVM tx hash, receipts can be queried using both TM tx hash and EVM tx hash. However, Blockscout has a problem when the tx hash on receipt does not match the one it queries. This happens when it use TM tx hash to query a receipt. This PR fixes the problem by override the tx hash on receipt with the requested tx hash.
=> Fix tx hashes mismatch

Jenkinsfile-PR.groovy
Expected `sha1` to contain commit id, but it contains branch path. Let's use `ghprbActualCommit` that actually contains the commit id.
=> Use actual commit id instead of branchname disguised as sha

Makefile
OSX builds are broken due to https://github.com/prometheus/procfs/issues/221
Locking down the Prometheus client to a specific revision is going to be a pain because of the other dependencies... really need to figure out how to vendor this package.
=> Add temp workaround for failing OSX builds

cmd/loom/chainconfig/cmd.go, cmd/loom/gateway/mapping_cmds.go, e2e/engine/cmd.go
Previously, `chain-cfg list-validators` command always shows all validators included the inactive one.
This pull request will show the current active validator only. 
Using `--all` flag to display the inactive validators.
ref : https://github.com/loomnetwork/loomchain/issues/1528
=> Add flag to show all validators on chainconfig command

rpc/query_server.go
https://github.com/loomnetwork/loomchain/issues/1540
If `from` address entered, set to use "eth" chain id or give an error if eth not supported.
If there is no `from` address, use loom.RootAddress(s.ChainID).
=> Modify eth_call to expect the From parameter to be an Ethereum address

rpc/client.go
Possable fix for websocket upgrading. [Changed to match the way tendermint does it.](https://github.com/loomnetwork/tendermint/blob/loomchain/rpc/lib/server/handlers.go#L755)
=> Websocket upgrading - checkOrigin always returns true

Makefile, store/multi_writer_app_store.go
Currently, pruning EVM keys every block forces Tendermint to create a new block faster so Blockscout indexer cannot catch up the speed and start to fall behind. This PR adds a new on-chain config, `PruneEvmKeysInterval`, which can be used to set pruning interval.   
Issue: https://github.com/loomnetwork/ops/issues/781
=> Prune old EVM keys every N blocks

rpc/eth/jsonrpc_conversion.go
The `blockTime` field on logs is confusing the Blockscout indexer and preventing it from indexing logs, I'm reverting the commit that added this field until we fix Blockscout.
=> Revert "Add block time to events & logs retrieved via Web3 JSON-RPC"

rpc/eth/jsonrpc_conversion.go
This was reverted in build 1331 because it broke the Blockscout indexer, we've adapted the indexer to deal with this field now so this can go back in.
=> Add block time to events & logs retrieved via Web3 JSON-RPC on the /eth endpoint

Makefile, features/features.go
This PRs adds `tg:v1.3` flag for the support of Binance Chain and Loom Coin precision adjustment.
=> Add TG v1.3 feature flag for precision adjustment on transfers via Binance Gateway

app.go
Currently, events are emitted immediately after tx is processed successfully. We should delay it since the state won't be available until the block is committed.
Issue: https://github.com/loomnetwork/loomchain/issues/1561
=> Emit tx events after block commit

plugin/validators_manager_v3.go
DPOS contract had insufficient funds to process a rewards claim during the election in block `9856178` so we have to delay this election to resume the chain. Once the chain is back up and running we can transfer some funds to the DPOS contract so the next election goes through.
=> Skip a botched DPOS election on extdev

Makefile
Newer versions use a different protobuf version that's not compatible with ours.
=> Lock down Prometheus golang client to v1.2.1

store/iavlstore.go, store/logstore.go, store/memstore.go, store/multi_writer_app_store.go, store/multi_writer_app_store_test.go, store/store.go, store/store_test.go, store/versioned_cachingstore.go, store/versioned_cachingstore_test.go
This is a follow up to PR #1532, cleans up a couple of issues left over from that PR:
- Eliminate GetSnapshot() from all the stores, only GetSnapshotAt() is used now.
- Fix VersionedCachingStore.GetSnapshotAt() to be atomic.
Also cleaned up the tests a little bit so they test using real stores instead of buggy mock stores.
=> Eliminate VersionedKVStore.GetSnapshot()

app.go, store/evmstore.go, store/evmstore_test.go, store/iavlstore.go, store/iavlstore_test.go, store/logstore.go, store/memstore.go, store/multi_writer_app_store.go, store/multi_writer_app_store_test.go, store/store.go, store/store_test.go, store/versioned_cachingstore.go, store/versioned_cachingstore_test.go
There was a bug in `EvmStore.Commit()` where it attempted to load the on-chain config from `evm.db`, but that's not where the on-chain config gets persisted to - it's persisted to `app.db`. This meant that the
flush interval specified in the on-chain config did not override the one specified in the `EvmStore` section in `loom.yml` as was originally intended.
=> Refactor the way the on-chain flush interval override is applied

app_test.go, cmd/loom/db/evm.go, cmd/loom/loom.go, config/config.go, e2e/chainconfig-loom.yaml, e2e/chainconfig-routine-loom.yaml, e2e/loom-3-loom.yaml, e2e/loom-4-loom.yaml, e2e/loom-5-loom.yaml, store/config.go, store/evmstore.go, store/evmstore_test.go, store/loomethdb.go, store/multi_writer_app_store.go, store/multi_writer_app_store_test.go
`MultiWriterAppStore` was used to migrate EVM state keys from app.db to evm.db, since all clusters have now been migrated this functionality is no longer necessary, and is in fact incompatible with the changes introduced in PR #1532.
This set of changes cleans out most of the obsolete code from that store:
- Eliminate writes to the `EvmStore` from `MultiWriterAppStore`.
- Eliminate Get/Has/Set/Delete from `EvmStore`.
- Eliminate use of `AppStore.SaveEVMStateToIAVL` config setting.
=> Cleanup MultiWriterAppStore

store/versioned_cachingstore.go
The caching provided by the `VersionedCachingStore` is of no benefit to nodes that aren't queried by clients because the transaction handlers bypass the cache. Since the vast majority of nodes, regardless of whether or not they're validators don't respond to client queries it makes more sense to disable the caching by default.
=> Disable the VersionedCachingStore by default

e2e/tests/truffle/test/EthFunctions.js, rpc/instrumenting.go, rpc/mock_query_server.go, rpc/query_server.go, rpc/query_service.go
This RPC method can be used to obtain the canonical tx hash from the EVM tx hash (which is just a hash of the tx receipt).
=> Add canonical_tx_hash RPC method on the /query interface

Makefile, builtin/plugins/dposv3/dpos.go, builtin/plugins/dposv3/dpos_test.go, cmd/loom/dposV3_commands.go, e2e/dposv3-unbond-all.toml
Add Validator Address as a target validator that the user need to unbond all of the delegations.
go-loom PR : https://github.com/loomnetwork/go-loom/pull/468
=> Quick fix for Dpos UnbondAll 

Makefile
This should keep everything building properly on Go 1.13 and earlier.
=> Lock down version of go-testing-interface package

Makefile, builtin/plugins/dposv3/dpos.go, builtin/plugins/dposv3/dpos_test.go, cmd/loom/dposV3_commands.go, features/features.go
This parameter is useful for setting up various DPOS scenarios on testnets.
The `dpos:v3.9` feature flag must be enabled for this parameter to have effect.
=> Add IgnoreUnbondLocktime to DPOS params

cmd/loom/dposV3_commands.go
`redelegate-all` can be used to randomly redistribute delegations from former validators to currently active validators.
=> Add dpos3 redelegate-all command

config/config.go
Had this sorting disabled on our Basechain nodes for a few weeks now, so should be safe to make it the default.
=> Disable key sorting in the EVM by default

cmd/loom/loom.go
Need more slots for testing on the testnet since we've previously used both gateway migration slots.
=> Add two more migration tx slots for testing

builtin/plugins/coin/coin_test.go
Don't register the same mock contract under different names. Doing so makes the fake registry's name -> address lookup non-deterministic.
=> Fix TestBurnAccess unit test

cmd/loom/config.go, config/config.go, config/gateway_config.go
This makes it easier to deploy the contract to the production cluster because validators won't have to mess about with `loom.yml`.
=> Load the bsc-gateway Go contract by default
